//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kombatant.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kombatant.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Face Target DISABLED.
        /// </summary>
        public static string Msg_AutoFaceTargetOff {
            get {
                return ResourceManager.GetString("Msg_AutoFaceTargetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Face Target ENABLED.
        /// </summary>
        public static string Msg_AutoFaceTargetOn {
            get {
                return ResourceManager.GetString("Msg_AutoFaceTargetOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous Mode DISABLED.
        /// </summary>
        public static string Msg_AutonomousOff {
            get {
                return ResourceManager.GetString("Msg_AutonomousOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autonomous Mode ENABLED.
        /// </summary>
        public static string Msg_AutonomousOn {
            get {
                return ResourceManager.GetString("Msg_AutonomousOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target is part of FATE &quot;{0}&quot;, syncing level....
        /// </summary>
        public static string Msg_AutoSyncFate {
            get {
                return ResourceManager.GetString("Msg_AutoSyncFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Targeting DISABLED.
        /// </summary>
        public static string Msg_AutoTargetOff {
            get {
                return ResourceManager.GetString("Msg_AutoTargetOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Targeting ENABLED.
        /// </summary>
        public static string Msg_AutoTargetOn {
            get {
                return ResourceManager.GetString("Msg_AutoTargetOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight is over.        ///Avoidance will RESUME.
        /// </summary>
        public static string Msg_AvoidanceDisabledOnBossEnd {
            get {
                return ResourceManager.GetString("Msg_AvoidanceDisabledOnBossEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting {0}!        ///Avoidance will PAUSE.
        /// </summary>
        public static string Msg_AvoidanceDisabledOnBossStart {
            get {
                return ResourceManager.GetString("Msg_AvoidanceDisabledOnBossStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoidance finished, stopping movement....
        /// </summary>
        public static string Msg_AvoidanceFinished {
            get {
                return ResourceManager.GetString("Msg_AvoidanceFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoidance DISABLED.
        /// </summary>
        public static string Msg_AvoidanceOff {
            get {
                return ResourceManager.GetString("Msg_AvoidanceOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoidance ENABLED.
        /// </summary>
        public static string Msg_AvoidanceOn {
            get {
                return ResourceManager.GetString("Msg_AvoidanceOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming Duty....
        /// </summary>
        public static string Msg_DutyConfirm {
            get {
                return ResourceManager.GetString("Msg_DutyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let the revels begin!.
        /// </summary>
        public static string Msg_DutyPsyche0 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise, rise to the occasion!.
        /// </summary>
        public static string Msg_DutyPsyche1 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Gil says someone is not going to accept....
        /// </summary>
        public static string Msg_DutyPsyche2 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So excited!.
        /// </summary>
        public static string Msg_DutyPsyche3 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And so are we!.
        /// </summary>
        public static string Msg_DutyPsyche4 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJOICE!.
        /// </summary>
        public static string Msg_DutyPsyche5 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiate soul extraction!.
        /// </summary>
        public static string Msg_DutyPsyche6 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behold, fury given form!.
        /// </summary>
        public static string Msg_DutyPsyche7 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more games!.
        /// </summary>
        public static string Msg_DutyPsyche8 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanics are for cars!.
        /// </summary>
        public static string Msg_DutyPsyche9 {
            get {
                return ResourceManager.GetString("Msg_DutyPsyche9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duty is ready!.
        /// </summary>
        public static string Msg_DutyReady {
            get {
                return ResourceManager.GetString("Msg_DutyReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fight is over. Avoidance will RESUME..
        /// </summary>
        public static string Msg_Log_AvoidanceDisabledOnBossEnd {
            get {
                return ResourceManager.GetString("Msg_Log_AvoidanceDisabledOnBossEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighting known boss. Avoidance will temporarily PAUSE..
        /// </summary>
        public static string Msg_Log_AvoidanceDisabledOnBossStart {
            get {
                return ResourceManager.GetString("Msg_Log_AvoidanceDisabledOnBossStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}!        ///Turn away before the cast completes!.
        /// </summary>
        public static string Msg_MechanicWarning_Gaze {
            get {
                return ResourceManager.GetString("Msg_MechanicWarning_Gaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}!        ///Stop moving or attacking!.
        /// </summary>
        public static string Msg_MechanicWarning_StandStill {
            get {
                return ResourceManager.GetString("Msg_MechanicWarning_StandStill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}!        ///Stop all activities before the timer reaches zero!.
        /// </summary>
        public static string Msg_MechanicWarning_StandStillOnZero {
            get {
                return ResourceManager.GetString("Msg_MechanicWarning_StandStillOnZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New target selected: {0} {1}.
        /// </summary>
        public static string Msg_NewTargetSelected {
            get {
                return ResourceManager.GetString("Msg_NewTargetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running at a tickrate other than 30 TPS!        ///See RebornBuddy log for more details..
        /// </summary>
        public static string Msg_Not30Tps {
            get {
                return ResourceManager.GetString("Msg_Not30Tps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///*************************** [ KOMBATANT WARNING! ] ***************************
        ///*                                                                            *
        ///* Operating at a tickrate other than 30! Botbase might not work as expected! *
        ///*    For optimal botbase performance, please set your TPS to exactly 30.     *
        ///*                                                                            *
        ///******************************************************************************
        ///        .
        /// </summary>
        public static string Msg_Not30Tps_Log {
            get {
                return ResourceManager.GetString("Msg_Not30Tps_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kombatant PAUSED.
        /// </summary>
        public static string Msg_Paused {
            get {
                return ResourceManager.GetString("Msg_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling {0}.
        /// </summary>
        public static string Msg_PulseFlagDisabled {
            get {
                return ResourceManager.GetString("Msg_PulseFlagDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling {0}.
        /// </summary>
        public static string Msg_PulseFlagEnabled {
            get {
                return ResourceManager.GetString("Msg_PulseFlagEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings have been reloaded..
        /// </summary>
        public static string Msg_ReloadedSettings {
            get {
                return ResourceManager.GetString("Msg_ReloadedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kombatant RESUMED.
        /// </summary>
        public static string Msg_Unpaused {
            get {
                return ResourceManager.GetString("Msg_Unpaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kombatant.
        /// </summary>
        public static string Name_Kombatant {
            get {
                return ResourceManager.GetString("Name_Kombatant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Commence Duty.
        /// </summary>
        public static string UI_AutoAcceptDutyFinder {
            get {
                return ResourceManager.GetString("UI_AutoAcceptDutyFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Accept Quests.
        /// </summary>
        public static string UI_AutoAcceptQuests {
            get {
                return ResourceManager.GetString("UI_AutoAcceptQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Advance Dialogue.
        /// </summary>
        public static string UI_AutoAdvanceDialogue {
            get {
                return ResourceManager.GetString("UI_AutoAdvanceDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto End ACT Encounters.
        /// </summary>
        public static string UI_AutoEndActEncounters {
            get {
                return ResourceManager.GetString("UI_AutoEndActEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Face Target.
        /// </summary>
        public static string UI_AutoFaceTarget {
            get {
                return ResourceManager.GetString("UI_AutoFaceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Skip Cutscenes.
        /// </summary>
        public static string UI_AutoSkipCutscenes {
            get {
                return ResourceManager.GetString("UI_AutoSkipCutscenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Sprint.
        /// </summary>
        public static string UI_AutoSprint {
            get {
                return ResourceManager.GetString("UI_AutoSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Sync to FATE.
        /// </summary>
        public static string UI_AutoSyncFate {
            get {
                return ResourceManager.GetString("UI_AutoSyncFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Target.
        /// </summary>
        public static string UI_AutoTarget {
            get {
                return ResourceManager.GetString("UI_AutoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Target Switching.
        /// </summary>
        public static string UI_AutoTargetSwitch {
            get {
                return ResourceManager.GetString("UI_AutoTargetSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat.
        /// </summary>
        public static string UI_Combat {
            get {
                return ResourceManager.GetString("UI_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combat Buff.
        /// </summary>
        public static string UI_CombatBuff {
            get {
                return ResourceManager.GetString("UI_CombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify When Ready.
        /// </summary>
        public static string UI_DutyFinderNotify {
            get {
                return ResourceManager.GetString("UI_DutyFinderNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Avoidance.
        /// </summary>
        public static string UI_EnableAvoidance {
            get {
                return ResourceManager.GetString("UI_EnableAvoidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable FATE mob filter.
        /// </summary>
        public static string UI_FateFilter {
            get {
                return ResourceManager.GetString("UI_FateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string UI_Header_About {
            get {
                return ResourceManager.GetString("UI_Header_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR Logic.
        /// </summary>
        public static string UI_Header_CombatRoutine {
            get {
                return ResourceManager.GetString("UI_Header_CombatRoutine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenience.
        /// </summary>
        public static string UI_Header_Convenience {
            get {
                return ResourceManager.GetString("UI_Header_Convenience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkeys.
        /// </summary>
        public static string UI_Header_Hotkeys {
            get {
                return ResourceManager.GetString("UI_Header_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movement.
        /// </summary>
        public static string UI_Header_Movement {
            get {
                return ResourceManager.GetString("UI_Header_Movement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeting.
        /// </summary>
        public static string UI_Header_Targeting {
            get {
                return ResourceManager.GetString("UI_Header_Targeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heal.
        /// </summary>
        public static string UI_Heal {
            get {
                return ResourceManager.GetString("UI_Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Autonomous Actions.
        /// </summary>
        public static string UI_IsAutonomous {
            get {
                return ResourceManager.GetString("UI_IsAutonomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string UI_IsPaused {
            get {
                return ResourceManager.GetString("UI_IsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Emote Command.
        /// </summary>
        public static string UI_Lbl_AutoEmoteCommand {
            get {
                return ResourceManager.GetString("UI_Lbl_AutoEmoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Emote Interval.
        /// </summary>
        public static string UI_Lbl_AutoEmoteInterval {
            get {
                return ResourceManager.GetString("UI_Lbl_AutoEmoteInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Selection Strategy.
        /// </summary>
        public static string UI_Lbl_AutoTargetingMode {
            get {
                return ResourceManager.GetString("UI_Lbl_AutoTargetingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds To Auto Commence.
        /// </summary>
        public static string UI_Lbl_DutyFinderWaitTime {
            get {
                return ResourceManager.GetString("UI_Lbl_DutyFinderWaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Mode.
        /// </summary>
        public static string UI_Lbl_FollowMode {
            get {
                return ResourceManager.GetString("UI_Lbl_FollowMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Distance for target scan.
        /// </summary>
        public static string UI_Lbl_TargetScanMaxDistance {
            get {
                return ResourceManager.GetString("UI_Lbl_TargetScanMaxDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint Generation.
        /// </summary>
        public static string UI_Lbl_WaypointGenerationMode {
            get {
                return ResourceManager.GetString("UI_Lbl_WaypointGenerationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanic Warnings.
        /// </summary>
        public static string UI_MechanicWarnings {
            get {
                return ResourceManager.GetString("UI_MechanicWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Avoidance on Bosses.
        /// </summary>
        public static string UI_PauseAvoidanceOnBosses {
            get {
                return ResourceManager.GetString("UI_PauseAvoidanceOnBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Combat Buff.
        /// </summary>
        public static string UI_PreCombatBuff {
            get {
                return ResourceManager.GetString("UI_PreCombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull.
        /// </summary>
        public static string UI_Pull {
            get {
                return ResourceManager.GetString("UI_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Buff.
        /// </summary>
        public static string UI_PullBuff {
            get {
                return ResourceManager.GetString("UI_PullBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        public static string UI_Rest {
            get {
                return ResourceManager.GetString("UI_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Combat Routine.
        /// </summary>
        public static string UI_SelectCr {
            get {
                return ResourceManager.GetString("UI_SelectCr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kombatant Settings.
        /// </summary>
        public static string UI_SettingsWindowTitle {
            get {
                return ResourceManager.GetString("UI_SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Pull.
        /// </summary>
        public static string UI_SmartPull {
            get {
                return ResourceManager.GetString("UI_SmartPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically commences a duty when it is ready..
        /// </summary>
        public static string UI_Tooltip_AutoAcceptDutyFinder {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoAcceptDutyFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically accept/complete quests..
        /// </summary>
        public static string UI_Tooltip_AutoAcceptQuests {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoAcceptQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically skip dialogue..
        /// </summary>
        public static string UI_Tooltip_AutoAdvanceDialogue {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoAdvanceDialogue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emote which should automatically be kept up, i.e. &quot;/grin motion&quot;.
        /// </summary>
        public static string UI_Tooltip_AutoEmoteCommand {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoEmoteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend the emote every x seconds..
        /// </summary>
        public static string UI_Tooltip_AutoEmoteInterval {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoEmoteInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will automatically send &quot;/echo end&quot; to the chat when no enemies are around for longer than 10 seconds..
        /// </summary>
        public static string UI_Tooltip_AutoEndActEncounters {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoEndActEncounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically face the target..
        /// </summary>
        public static string UI_Tooltip_AutoFaceTarget {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoFaceTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically skip cutscenes..
        /// </summary>
        public static string UI_Tooltip_AutoSkipCutscenes {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoSkipCutscenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically sprint whenever the action is available..
        /// </summary>
        public static string UI_Tooltip_AutoSprint {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoSprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically syncs to a FATE when a FATE mob is selected as your target..
        /// </summary>
        public static string UI_Tooltip_AutoSyncFate {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoSyncFate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic targeting logic..
        /// </summary>
        public static string UI_Tooltip_AutoTarget {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables/disables automatic selection of a new target, even when the old one is still alive..
        /// </summary>
        public static string UI_Tooltip_AutoTargetSwitch {
            get {
                return ResourceManager.GetString("UI_Tooltip_AutoTargetSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the combat routine to execute the Combat behavior..
        /// </summary>
        public static string UI_Tooltip_Combat {
            get {
                return ResourceManager.GetString("UI_Tooltip_Combat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the combat routine to execute the CombatBuff behavior..
        /// </summary>
        public static string UI_Tooltip_CombatBuff {
            get {
                return ResourceManager.GetString("UI_Tooltip_CombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a random sound effect when the Duty Finder is ready..
        /// </summary>
        public static string UI_Tooltip_DutyFinderNotify {
            get {
                return ResourceManager.GetString("UI_Tooltip_DutyFinderNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow RebornBuddy to avoid telegraphed attacks..
        /// </summary>
        public static string UI_Tooltip_EnableAvoidance {
            get {
                return ResourceManager.GetString("UI_Tooltip_EnableAvoidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, targeting strategies will target FATE mobs as long as the player is inside a FATE area..
        /// </summary>
        public static string UI_Tooltip_FateFilter {
            get {
                return ResourceManager.GetString("UI_Tooltip_FateFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the combat routine to execute the Heal behavior..
        /// </summary>
        public static string UI_Tooltip_Heal {
            get {
                return ResourceManager.GetString("UI_Tooltip_Heal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When enabled, other components will treat this botbase as one without user input. This will cause combat routines to autonmatically move into the correct positions etc..
        /// </summary>
        public static string UI_Tooltip_IsAutonomous {
            get {
                return ResourceManager.GetString("UI_Tooltip_IsAutonomous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable the combat assist temporarily. Please note that Kombatant will always start paused..
        /// </summary>
        public static string UI_Tooltip_IsPaused {
            get {
                return ResourceManager.GetString("UI_Tooltip_IsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will take control from the player when certain attacks occur..
        /// </summary>
        public static string UI_Tooltip_MechanicWarnings {
            get {
                return ResourceManager.GetString("UI_Tooltip_MechanicWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will automatically pause avoidance when engaging a known boss..
        /// </summary>
        public static string UI_Tooltip_PauseAvoidanceOnBosses {
            get {
                return ResourceManager.GetString("UI_Tooltip_PauseAvoidanceOnBosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the combat routine to execute the PreCombatBuff behavior..
        /// </summary>
        public static string UI_Tooltip_PreCombatBuff {
            get {
                return ResourceManager.GetString("UI_Tooltip_PreCombatBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the combat routine to execute the Pull behavior..
        /// </summary>
        public static string UI_Tooltip_Pull {
            get {
                return ResourceManager.GetString("UI_Tooltip_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the combat routine to execute the PullBuff behavior..
        /// </summary>
        public static string UI_Tooltip_PullBuff {
            get {
                return ResourceManager.GetString("UI_Tooltip_PullBuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the combat routine to execute the Rest behavior..
        /// </summary>
        public static string UI_Tooltip_Rest {
            get {
                return ResourceManager.GetString("UI_Tooltip_Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a non-tank, do not engage enemies before your tank..
        /// </summary>
        public static string UI_Tooltip_SmartPull {
            get {
                return ResourceManager.GetString("UI_Tooltip_SmartPull", resourceCulture);
            }
        }
    }
}
